### ISSUE TITLE
create syncthing yaml/script to sync the capnp files and others

### ISSUE THREAD

**Issue by abdulrahmantkhalifa** [0-complexity/openvcloud_installer#23]
create syncthing yaml/script to sync the capnp files and others, to allow the syncthings to discover each other and sync the files between nodes

**Comment by abdulrahmantkhalifa** [comment]
check the paths in the config are synced : https://github.com/0-complexity/openvcloud_installer/blob/master/scripts/kubernetes/config/system-config.yaml#L89

**Comment by ahmedelsayed-93** [comment]
```/var/ovc/0-access```, ```/var/ovc/influx``` directories  is not synchronized

![image](https://user-images.githubusercontent.com/24386820/35800720-7c35fec0-0a72-11e8-89cc-886966af30cd.png)

**Comment by grimpy** [comment]
redeployed be-g8-4 containers please check again

**Comment by ahmedelsayed-93** [comment]
![image](https://user-images.githubusercontent.com/24386820/35813084-5bd4c87c-0a9b-11e8-9617-e1eca1061bbe.png)

be-g8-4-loc-ctr-03 is not synchronizated

**Comment by ahmedelsayed-93** [comment]
be-g8-4-loc-ctr-02 is not synchronizated

![image](https://user-images.githubusercontent.com/24386820/35906751-6a2a9910-0bf4-11e8-81b7-0a40036ced6c.png)

**Comment by ahmedelsayed-93** [comment]
verified on be-g8-3
