### ISSUE TITLE
USB stick controller node os installer image generator

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud_installer#32]
Based on the environment yaml file, we need generate a usb stick image that we can use to install the controllers.

The image should contain 1 generated install script that the ops can use to install the or after booting the controller using the usb stick. This generated script will have 1 argument to pass which contoller node needs to be installed:

Eg: install controller 2 would go as follows:
```bash
/root# install 2
...
```

**Comment by Dinaamagdy** [comment]
tested by ops team
